---
#create user
#
- hosts: qaserver
  become: yes
  ignore_errors: yes 
  tasks:
    - name: Install packages
      package:
        name: {{ item }}
        state: present
      with_items:
          - unzip
          - wget
          - httpd
           
